// CONCURSO
const SET_CURRENT_CONCURSO = `SET_CURRENT_CONCURSO`
const GET_CURRENT_CONCURSO = `GET_CURRENT_CONCURSO`
const UPDATE_CONCURSO = `UPDATE_CONCURSO`
const DELETE_CONCURSO = `DELETE_CONCURSO`
const CREATE_CONCURSO = `CREATE_CONCURSO`
// JURI
const SET_CURRENT_JURADO = `SET_CURRENT_JURADO`
const CREATE_JURADO = `CREATE_JURADO`
const DELETE_JURADO = `DELETE_JURADO`
const UPDATE_JURADO = `UPDATE_JURADO`
const GET_JURADOS = `GET_JURADOS`
// USUARIO
const GET_USER_INFO = `GET_USER_INFO`
const SET_TOKEN = `SET_TOKEN`
const GET_TOKEN = `GET_TOKEN`
const CREATE_USER = `CREATE_USER`
const SET_TOKEN_NEW_USER = `SET_TOKEN_NEW_USER`
const DELETE_USER = `DELETE_USER`
const UPDATE_USER = `UPDATE_USER`
const GET_USERS = `GET_USERS`
// GERAL
const GET_CONCURSOS = `GET_CONCURSOS`
const SET_CONCURSOS = `SET_CONCURSOS`

export default {
  SET_CURRENT_CONCURSO,
  GET_CURRENT_CONCURSO,
  UPDATE_CONCURSO,
  DELETE_CONCURSO,
  CREATE_CONCURSO,
  SET_CURRENT_JURADO,
  CREATE_JURADO,
  DELETE_JURADO,
  UPDATE_JURADO,
  GET_JURADOS,
  GET_USER_INFO,
  SET_TOKEN,
  GET_TOKEN,
  CREATE_USER,
  SET_TOKEN_NEW_USER,
  DELETE_USER,
  UPDATE_USER,
  GET_USERS,
  GET_CONCURSOS,
  SET_CONCURSOS
}
